name = "tccane-website"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "38a057da08d74254854b3b4a9fcb9cf4"
preview_id = "REPLACE_WITH_RATE_LIMIT_KV_PREVIEW_ID"

[[kv_namespaces]]
binding = "DLQ_KV"
id = "63dc821d849d41aea8ab64ed4ca2ec96"
preview_id = "REPLACE_WITH_DLQ_KV_PREVIEW_ID"

[vars]
RATE_LIMIT_MAX = "5"
RATE_LIMIT_WINDOW_SECONDS = "600"
GOOGLE_SHEET_TAB = "Submissions"
TURNSTILE_SITE_KEY = "0x4AAAAAAEJtP1eUYxGq97FQ"
